#!/bin/bash -x
* * * * * python3 /app/test.py >> /var/log/cron.log
*/25 */6 * * * python3 /app/analysis/analyse_aggregate.py >> /var/log/analyse_aggregate.log
*/30 */6 * * * python3 /app/analysis/analyse_gran.py >> /var/log/analyse_gran.log
# 0 */5* * * pkill -f main.py && echo "Restarting Program" && python3 /app/main.py >> /var/log/main.log 
